experiment_name: test_imdb
n_repeats: 1
scenario_params_list:
 - dataset_name:
    - 'imdb'
   partners_count:
    - 3
   amounts_per_partner: 
    - [0.2, 0.5, 0.3]
   samples_split_option:
    - ['advanced', [[1, 'shared'], [1, 'shared'], [1, 'specific']]]
   multi_partner_learning_approach:
    - 'fedavg'
   aggregation_weighting:
    - 'uniform'
   methods:
    - ["Shapley values", "Independent scores"]
   gradient_updates_per_pass_count:
    - 5
   is_quick_demo:
    - True
