experiment_name: my_example
n_repeats: 5
scenario_params_list:
 - dataset_name:
     - 'titanic'
   partners_count:
     - 3
   amounts_per_partner:
     - [0.4, 0.3, 0.3]
   samples_split_option:
     - ['basic', 'random']
   multi_partner_learning_approach:
     - 'fedavg'
   aggregation_weighting:
     - 'uniform'
   epoch_count:
     - 1
   methods:
     - ["Shapley values", "Independent scores", "TMCS"]
   minibatch_count:
     - 20
   gradient_updates_per_pass_count:
     - 8
